using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace CodeBrix.VideoPlayback.Color.Luts;

/// <summary>
/// Reads and writes the ".cube" lookup-table files colour-grading tools export - the only lookup-table
/// format this library supports.
/// </summary>
/// <remarks>
/// <para>
/// The format is a plain text file: some keywords, then a list of triplets. <c>LUT_3D_SIZE n</c> introduces
/// <c>n * n * n</c> triplets with red changing fastest; <c>LUT_1D_SIZE n</c> introduces <c>n</c> triplets,
/// one per point of three per-channel curves. <c>TITLE</c> names the table, <c>DOMAIN_MIN</c> and
/// <c>DOMAIN_MAX</c> state the range of input the table covers, blank lines and lines beginning with
/// <c>#</c> are ignored, and either line ending is accepted. A <c>#</c> part way along a line is a comment
/// too, which is how a title with a note after it is read correctly.
/// </para>
/// <para>
/// <b>What else is accepted.</b> <c>LUT_1D_INPUT_RANGE</c> and <c>LUT_3D_INPUT_RANGE</c> state a domain for
/// one of the two tables instead of both. A file stating BOTH sizes is a COMBINED file - a 1-D shaper and
/// the 3-D table it feeds, the arrangement DaVinci Resolve's dialect allows - and its rows are read as the
/// shaper's block followed by the table's, in the order the two sizes were declared. Values outside the
/// declared domain are ordinary: a table's OUTPUT is whatever the file says, and only the INPUT is
/// normalised.
/// </para>
/// <para>
/// <b>Writing.</b> <see cref="Write(Lut3D, string, string)" /> emits the same format: LF line endings, the
/// invariant culture, plain decimal numbers - never scientific notation - and the shortest digits that read
/// back as the very same value, so a file that is read and written again holds the same numbers it started
/// with. That is the file the authoring pipeline hands to FFmpeg's <c>lut3d</c> filter.
/// </para>
/// </remarks>
public static class CubeLutFile
{
    /// <summary>The line this writer puts at the top of every file it produces.</summary>
    public const string GeneratorComment = "# Generated by CodeBrix.VideoPlayback";

    private static readonly UTF8Encoding FileEncoding = new UTF8Encoding(false);

    /// <summary>Reads a ".cube" file from disk.</summary>
    /// <param name="path">The file's path.</param>
    /// <returns>The table the file holds, named after the file (or after its TITLE).</returns>
    /// <exception cref="ArgumentException"><paramref name="path" /> is null or blank.</exception>
    /// <exception cref="FileNotFoundException">The file does not exist.</exception>
    /// <exception cref="InvalidDataException">The file is not a readable ".cube" table.</exception>
    public static CubeLut ReadFile(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            throw new ArgumentException("A path to the .cube file is required.", nameof(path));
        }

        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"There is no .cube lookup-table file at '{path}'.", path);
        }

        return Parse(File.ReadAllText(path), Path.GetFileNameWithoutExtension(path));
    }

    /// <summary>Reads a ".cube" table from a stream.</summary>
    /// <param name="stream">The stream, read to its end and left open.</param>
    /// <param name="fallbackName">
    /// The name to give the table when the text carries no TITLE. May be null, in which case a generic name
    /// is used.
    /// </param>
    /// <returns>The table the stream holds.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="stream" /> is null.</exception>
    /// <exception cref="InvalidDataException">The text is not a readable ".cube" table.</exception>
    public static CubeLut Read(Stream stream, string fallbackName = null)
    {
        if (stream == null) throw new ArgumentNullException(nameof(stream));

        using StreamReader reader = new StreamReader(stream, Encoding.UTF8, true, 4096, true);
        return Parse(reader.ReadToEnd(), fallbackName);
    }

    /// <summary>Parses the text of a ".cube" file.</summary>
    /// <param name="text">The file's whole text.</param>
    /// <param name="fallbackName">
    /// The name to give the table when the file carries no TITLE. May be null, in which case a generic name
    /// is used.
    /// </param>
    /// <returns>The table the text describes.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="text" /> is null.</exception>
    /// <exception cref="InvalidDataException">The text is not a readable ".cube" table.</exception>
    public static CubeLut Parse(string text, string fallbackName = null)
    {
        if (text == null) throw new ArgumentNullException(nameof(text));

        string title = null;
        int size3D = 0;
        int size1D = 0;
        bool curvesDeclaredFirst = false;
        List<float> values = new List<float>();

        float[] sharedMinimum = null;
        float[] sharedMaximum = null;
        float[] minimum1D = null;
        float[] maximum1D = null;
        float[] minimum3D = null;
        float[] maximum3D = null;

        int lineNumber = 0;
        foreach (string rawLine in text.Split('\n'))
        {
            lineNumber++;
            string line = rawLine.Trim();
            if (line.Length == 0 || line[0] == '#') continue;

            string rest;

            if (Keyword(line, "TITLE", out rest))
            {
                title = ReadTitle(rest);
                continue;
            }

            line = StripComment(line);
            if (line.Length == 0) continue;

            if (Keyword(line, "LUT_3D_SIZE", out rest))
            {
                size3D = ReadSize(rest, lineNumber, "LUT_3D_SIZE", Lut3D.MinimumSize, Lut3D.MaximumSize);
                if (size1D == 0) curvesDeclaredFirst = false;
                continue;
            }

            if (Keyword(line, "LUT_1D_SIZE", out rest))
            {
                size1D = ReadSize(rest, lineNumber, "LUT_1D_SIZE", Lut1D.MinimumSize, Lut1D.MaximumSize);
                if (size3D == 0) curvesDeclaredFirst = true;
                continue;
            }

            if (Keyword(line, "DOMAIN_MIN", out rest))
            {
                sharedMinimum = ReadTriplet(rest, lineNumber, "DOMAIN_MIN");
                continue;
            }

            if (Keyword(line, "DOMAIN_MAX", out rest))
            {
                sharedMaximum = ReadTriplet(rest, lineNumber, "DOMAIN_MAX");
                continue;
            }

            if (Keyword(line, "LUT_1D_INPUT_RANGE", out rest))
            {
                float[] range = ReadNumbers(rest, lineNumber, "LUT_1D_INPUT_RANGE", 2);
                minimum1D = new[] { range[0], range[0], range[0] };
                maximum1D = new[] { range[1], range[1], range[1] };
                continue;
            }

            if (Keyword(line, "LUT_3D_INPUT_RANGE", out rest))
            {
                float[] range = ReadNumbers(rest, lineNumber, "LUT_3D_INPUT_RANGE", 2);
                minimum3D = new[] { range[0], range[0], range[0] };
                maximum3D = new[] { range[1], range[1], range[1] };
                continue;
            }

            float[] triplet = ReadTriplet(line, lineNumber, "a table row");
            values.Add(triplet[0]);
            values.Add(triplet[1]);
            values.Add(triplet[2]);
        }

        float[] domain1DMinimum = Domain(minimum1D, sharedMinimum, 0f);
        float[] domain1DMaximum = Domain(maximum1D, sharedMaximum, 1f);
        float[] domain3DMinimum = Domain(minimum3D, sharedMinimum, 0f);
        float[] domain3DMaximum = Domain(maximum3D, sharedMaximum, 1f);

        if (size1D > 0) EnsureRisingDomain(domain1DMinimum, domain1DMaximum);
        if (size3D > 0) EnsureRisingDomain(domain3DMinimum, domain3DMaximum);

        string name = !string.IsNullOrWhiteSpace(title)
            ? title
            : (!string.IsNullOrWhiteSpace(fallbackName) ? fallbackName : "cube lookup table");

        if (size3D > 0 && size1D > 0)
        {
            return ParseCombined(
                values,
                size1D,
                size3D,
                curvesDeclaredFirst,
                domain1DMinimum,
                domain1DMaximum,
                domain3DMinimum,
                domain3DMaximum,
                title,
                name);
        }

        if (size3D > 0)
        {
            int expected = size3D * size3D * size3D * 3;
            if (values.Count != expected)
            {
                throw new InvalidDataException(
                    $"This .cube file states LUT_3D_SIZE {size3D}, which needs {expected / 3} rows of three "
                    + $"numbers; it holds {values.Count / 3}.");
            }

            return new CubeLut(
                BuildTable(size3D, values.ToArray(), domain3DMinimum, domain3DMaximum),
                title,
                name);
        }

        if (size1D > 0)
        {
            if (values.Count != size1D * 3)
            {
                throw new InvalidDataException(
                    $"This .cube file states LUT_1D_SIZE {size1D}, which needs {size1D} rows of three "
                    + $"numbers; it holds {values.Count / 3}.");
            }

            return new CubeLut(
                BuildCurves(values, 0, size1D, domain1DMinimum, domain1DMaximum),
                title,
                name);
        }

        throw new InvalidDataException(
            "This text states neither LUT_3D_SIZE nor LUT_1D_SIZE, so it is not a .cube lookup table. Every "
            + "such file names its table's size before its rows.");
    }

    /// <summary>Writes a three-dimensional table to a ".cube" file, replacing anything already there.</summary>
    /// <param name="lut">The table to write.</param>
    /// <param name="path">Where to write it. Any folders in the path must already exist.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> is null.</exception>
    /// <exception cref="ArgumentException"><paramref name="path" /> is null or blank.</exception>
    public static void Write(Lut3D lut, string path, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));
        if (string.IsNullOrWhiteSpace(path))
        {
            throw new ArgumentException("A path to write the .cube file to is required.", nameof(path));
        }

        using StreamWriter writer = CreateWriter(File.Create(path), false);
        Write(lut, writer, title);
    }

    /// <summary>Writes per-channel curves to a ".cube" file, replacing anything already there.</summary>
    /// <param name="lut">The curves to write.</param>
    /// <param name="path">Where to write them. Any folders in the path must already exist.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> is null.</exception>
    /// <exception cref="ArgumentException"><paramref name="path" /> is null or blank.</exception>
    public static void Write(Lut1D lut, string path, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));
        if (string.IsNullOrWhiteSpace(path))
        {
            throw new ArgumentException("A path to write the .cube file to is required.", nameof(path));
        }

        using StreamWriter writer = CreateWriter(File.Create(path), false);
        Write(lut, writer, title);
    }

    /// <summary>Writes a three-dimensional table to a stream.</summary>
    /// <param name="lut">The table to write.</param>
    /// <param name="stream">The stream to write to. It is flushed but left open.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> or <paramref name="stream" /> is null.</exception>
    public static void Write(Lut3D lut, Stream stream, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));
        if (stream == null) throw new ArgumentNullException(nameof(stream));

        using StreamWriter writer = CreateWriter(stream, true);
        Write(lut, writer, title);
    }

    /// <summary>Writes per-channel curves to a stream.</summary>
    /// <param name="lut">The curves to write.</param>
    /// <param name="stream">The stream to write to. It is flushed but left open.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> or <paramref name="stream" /> is null.</exception>
    public static void Write(Lut1D lut, Stream stream, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));
        if (stream == null) throw new ArgumentNullException(nameof(stream));

        using StreamWriter writer = CreateWriter(stream, true);
        Write(lut, writer, title);
    }

    /// <summary>Renders a three-dimensional table as the text of a ".cube" file.</summary>
    /// <param name="lut">The table.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <returns>The whole file, with LF line endings.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> is null.</exception>
    /// <remarks>A 65-node table is some seven megabytes of text; prefer a stream for anything large.</remarks>
    public static string ToText(Lut3D lut, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));

        StringWriter writer = new StringWriter(CultureInfo.InvariantCulture) { NewLine = "\n" };
        Write(lut, writer, title);
        return writer.ToString();
    }

    /// <summary>Renders per-channel curves as the text of a ".cube" file.</summary>
    /// <param name="lut">The curves.</param>
    /// <param name="title">The TITLE to state, or null to state none.</param>
    /// <returns>The whole file, with LF line endings.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="lut" /> is null.</exception>
    public static string ToText(Lut1D lut, string title = null)
    {
        if (lut == null) throw new ArgumentNullException(nameof(lut));

        StringWriter writer = new StringWriter(CultureInfo.InvariantCulture) { NewLine = "\n" };
        Write(lut, writer, title);
        return writer.ToString();
    }

    /// <summary>Formats one number the way this writer does: plain decimal, invariant, and reversible.</summary>
    /// <param name="value">The number.</param>
    /// <returns>The number in plain decimal notation, never in exponent form.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The number is not finite.</exception>
    /// <remarks>
    /// The digits are the shortest set that reads back as the very same <see cref="float" />, so a value
    /// written and read again is bit-for-bit what it was. Where the runtime would have chosen exponent
    /// notation - for a very small or very large number - the digits are shifted into plain notation
    /// instead, because the ".cube" format has no exponent form.
    /// </remarks>
    public static string Format(float value)
    {
        if (float.IsNaN(value) || float.IsInfinity(value))
        {
            throw new ArgumentOutOfRangeException(
                nameof(value),
                value,
                "A .cube file holds finite numbers only.");
        }

        string text = value.ToString("R", CultureInfo.InvariantCulture);
        int exponentAt = text.IndexOf('E');
        if (exponentAt < 0) return text.IndexOf('.') < 0 ? text + ".0" : text;

        return Expand(text, exponentAt);
    }

    private static StreamWriter CreateWriter(Stream stream, bool leaveOpen) =>
        new StreamWriter(stream, FileEncoding, 65536, leaveOpen) { NewLine = "\n" };

    private static void Write(Lut3D lut, TextWriter writer, string title)
    {
        WriteHeader(writer, title, "LUT_3D_SIZE", lut.Size, lut.DomainMinimum, lut.DomainMaximum);

        ReadOnlySpan<float> values = lut.Values;
        for (int index = 0; index < values.Length; index += 3)
        {
            WriteTriplet(writer, values[index], values[index + 1], values[index + 2]);
        }
    }

    private static void Write(Lut1D lut, TextWriter writer, string title)
    {
        WriteHeader(writer, title, "LUT_1D_SIZE", lut.Size, lut.DomainMinimum, lut.DomainMaximum);

        ReadOnlySpan<float> red = lut.Red;
        ReadOnlySpan<float> green = lut.Green;
        ReadOnlySpan<float> blue = lut.Blue;
        for (int index = 0; index < red.Length; index++)
        {
            WriteTriplet(writer, red[index], green[index], blue[index]);
        }
    }

    private static void WriteHeader(
        TextWriter writer,
        string title,
        string sizeKeyword,
        int size,
        ReadOnlySpan<float> domainMinimum,
        ReadOnlySpan<float> domainMaximum)
    {
        writer.WriteLine(GeneratorComment);

        string cleaned = CleanTitle(title);
        if (cleaned != null) writer.WriteLine("TITLE \"" + cleaned + "\"");

        writer.WriteLine(sizeKeyword + " " + size.ToString(CultureInfo.InvariantCulture));

        bool defaultDomain =
            domainMinimum[0] == 0f && domainMinimum[1] == 0f && domainMinimum[2] == 0f
            && domainMaximum[0] == 1f && domainMaximum[1] == 1f && domainMaximum[2] == 1f;

        if (!defaultDomain)
        {
            writer.WriteLine(
                "DOMAIN_MIN " + Format(domainMinimum[0]) + " " + Format(domainMinimum[1]) + " "
                + Format(domainMinimum[2]));

            writer.WriteLine(
                "DOMAIN_MAX " + Format(domainMaximum[0]) + " " + Format(domainMaximum[1]) + " "
                + Format(domainMaximum[2]));
        }

        writer.WriteLine();
    }

    private static void WriteTriplet(TextWriter writer, float red, float green, float blue) =>
        writer.WriteLine(Format(red) + " " + Format(green) + " " + Format(blue));

    private static string CleanTitle(string title)
    {
        if (string.IsNullOrWhiteSpace(title)) return null;

        StringBuilder builder = new StringBuilder(title.Length);
        foreach (char character in title)
        {
            if (character == '"') continue;
            builder.Append(character < ' ' ? ' ' : character);
        }

        string cleaned = builder.ToString().Trim();
        return cleaned.Length == 0 ? null : cleaned;
    }

    private static string Expand(string text, int exponentAt)
    {
        string body = text.Substring(0, exponentAt);
        int exponent = int.Parse(
            text.Substring(exponentAt + 1),
            NumberStyles.Integer | NumberStyles.AllowLeadingSign,
            CultureInfo.InvariantCulture);

        string sign = string.Empty;
        if (body.Length > 0 && (body[0] == '-' || body[0] == '+'))
        {
            if (body[0] == '-') sign = "-";
            body = body.Substring(1);
        }

        int dot = body.IndexOf('.');
        string digits = dot < 0 ? body : body.Remove(dot, 1);
        int pointPosition = (dot < 0 ? body.Length : dot) + exponent;

        if (pointPosition <= 0)
        {
            return sign + "0." + new string('0', -pointPosition) + digits;
        }

        if (pointPosition >= digits.Length)
        {
            return sign + digits + new string('0', pointPosition - digits.Length) + ".0";
        }

        return sign + digits.Insert(pointPosition, ".");
    }

    private static CubeLut ParseCombined(
        List<float> values,
        int size1D,
        int size3D,
        bool curvesDeclaredFirst,
        float[] domain1DMinimum,
        float[] domain1DMaximum,
        float[] domain3DMinimum,
        float[] domain3DMaximum,
        string title,
        string name)
    {
        int rows3D = size3D * size3D * size3D;
        int expected = (size1D + rows3D) * 3;

        if (values.Count != expected)
        {
            throw new InvalidDataException(
                $"This .cube file states LUT_1D_SIZE {size1D} AND LUT_3D_SIZE {size3D} - a shaper and the "
                + $"table it feeds - which together need {size1D + rows3D} rows of three numbers; it holds "
                + $"{values.Count / 3}.");
        }

        int curvesAt = curvesDeclaredFirst ? 0 : rows3D * 3;
        int tableAt = curvesDeclaredFirst ? size1D * 3 : 0;

        Lut1D shaper = BuildCurves(values, curvesAt, size1D, domain1DMinimum, domain1DMaximum);

        float[] grid = new float[rows3D * 3];
        values.CopyTo(tableAt, grid, 0, grid.Length);

        return new CubeLut(
            shaper,
            BuildTable(size3D, grid, domain3DMinimum, domain3DMaximum),
            title,
            name);
    }

    private static Lut3D BuildTable(int size, float[] grid, float[] minimum, float[] maximum)
    {
        try
        {
            return new Lut3D(size, grid, minimum, maximum);
        }
        catch (ArgumentException ex)
        {
            // Nothing above should let this happen; if a shape slips through, it is still a bad FILE and is
            // reported as one rather than as a programming error in the caller.
            throw new InvalidDataException(
                "This .cube file states a three-dimensional table this reader cannot build: " + ex.Message,
                ex);
        }
    }

    private static Lut1D BuildCurves(List<float> values, int offset, int size, float[] minimum, float[] maximum)
    {
        try
        {
            return ReadCurves(values, offset, size, minimum, maximum);
        }
        catch (ArgumentException ex)
        {
            throw new InvalidDataException(
                "This .cube file states curves this reader cannot build: " + ex.Message,
                ex);
        }
    }

    private static Lut1D ReadCurves(List<float> values, int offset, int size, float[] minimum, float[] maximum)
    {
        float[] red = new float[size];
        float[] green = new float[size];
        float[] blue = new float[size];

        for (int point = 0; point < size; point++)
        {
            int at = offset + (point * 3);
            red[point] = values[at];
            green[point] = values[at + 1];
            blue[point] = values[at + 2];
        }

        return new Lut1D(red, green, blue, minimum, maximum);
    }

    private static float[] Domain(float[] specific, float[] shared, float fallback) =>
        specific ?? shared ?? new[] { fallback, fallback, fallback };

    private static void EnsureRisingDomain(float[] minimum, float[] maximum)
    {
        for (int channel = 0; channel < 3; channel++)
        {
            if (maximum[channel] > minimum[channel]) continue;

            throw new InvalidDataException(
                "This .cube file states an input domain that does not rise: channel "
                + channel.ToString(CultureInfo.InvariantCulture) + " runs from "
                + Format(minimum[channel]) + " to " + Format(maximum[channel])
                + ". The maximum must be above the minimum on every channel.");
        }
    }

    private static string ReadTitle(string rest)
    {
        string text = rest.Trim();
        if (text.Length == 0) return null;

        if (text[0] == '"')
        {
            int closing = text.IndexOf('"', 1);
            return closing < 0 ? text.Substring(1).Trim() : text.Substring(1, closing - 1);
        }

        return StripComment(text).Trim();
    }

    private static string StripComment(string line)
    {
        int hash = line.IndexOf('#');
        return hash < 0 ? line : line.Substring(0, hash).TrimEnd();
    }

    private static bool Keyword(string line, string keyword, out string rest)
    {
        rest = null;

        if (line.Length < keyword.Length
            || string.Compare(line, 0, keyword, 0, keyword.Length, StringComparison.OrdinalIgnoreCase) != 0)
        {
            return false;
        }

        if (line.Length == keyword.Length)
        {
            rest = string.Empty;
            return true;
        }

        char next = line[keyword.Length];
        if (next != ' ' && next != '\t') return false;

        rest = line.Substring(keyword.Length);
        return true;
    }

    private static int ReadSize(string text, int lineNumber, string keyword, int minimum, int maximum)
    {
        if (!int.TryParse(text.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out int value)
            || value <= 0)
        {
            throw new InvalidDataException(
                $"Line {lineNumber} of this .cube file states '{keyword}' followed by '{text.Trim()}', which "
                + "is not a positive whole number.");
        }

        if (value < minimum || value > maximum)
        {
            throw new InvalidDataException(
                $"Line {lineNumber} of this .cube file states '{keyword} {value}'; this reader accepts "
                + $"{minimum} to {maximum}.");
        }

        return value;
    }

    private static float[] ReadTriplet(string text, int lineNumber, string what) =>
        ReadNumbers(text, lineNumber, what, 3);

    private static float[] ReadNumbers(string text, int lineNumber, string what, int count)
    {
        string[] parts = text.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length != count)
        {
            throw new InvalidDataException(
                $"Line {lineNumber} of this .cube file should hold {count} numbers for {what}; it holds "
                + $"{parts.Length}: '{text.Trim()}'.");
        }

        float[] numbers = new float[count];
        for (int i = 0; i < count; i++)
        {
            if (!float.TryParse(parts[i], NumberStyles.Float, CultureInfo.InvariantCulture, out numbers[i])
                || float.IsNaN(numbers[i])
                || float.IsInfinity(numbers[i]))
            {
                throw new InvalidDataException(
                    $"Line {lineNumber} of this .cube file holds '{parts[i]}' where {what} needs a finite "
                    + "number.");
            }
        }

        return numbers;
    }
}
