#!/usr/bin/env python3
# generate-luts.py - writes the self-generated part of this repository's .cube LUT corpus.
#
# Written for CodeBrix.VideoPlayback. The author places this script, and every file it writes,
# in the PUBLIC DOMAIN (Creative Commons CC0 1.0 Universal). No rights reserved.
#
# Python 3 standard library only: no third-party package is imported, installed or needed.
#
# The output is DETERMINISTIC. Every number is written with "%.6f" formatting, which in Python is
# locale-independent, so the bytes are identical on every machine and in every locale. Running the
# script twice over the same output folder rewrites byte-identical files.
#
# Usage:
#     python3 generate-luts.py [output-folder]
#
# The default output folder is the "generated" folder beside this script.
#
# Every table's mathematical definition is stated in the DEFINITIONS dictionary below, is repeated in
# the comment header of the file it produces, and is recorded in MANIFEST.txt so that tests can
# assert computed values against it.

import os
import sys

# ----------------------------------------------------------------------------------------------
# Formatting: invariant, deterministic, six decimal places.
# ----------------------------------------------------------------------------------------------

DECIMALS = 6


def fmt(value):
    """Formats one number the one way this script ever formats numbers."""
    if value == 0:          # also catches -0.0, which would otherwise print as "-0.000000"
        value = 0.0
    return "%.*f" % (DECIMALS, value)


def row(red, green, blue):
    """Formats one table row."""
    return fmt(red) + " " + fmt(green) + " " + fmt(blue)


def clamp(value, low=0.0, high=1.0):
    """Clamps one number into a range."""
    return low if value < low else (high if value > high else value)


# ----------------------------------------------------------------------------------------------
# The transforms. Each takes r, g, b in 0..1 and returns a clamped triplet.
# ----------------------------------------------------------------------------------------------

def t_identity(r, g, b):
    return (r, g, b)


def t_warm(r, g, b):
    return (clamp(r * 1.060000), clamp(g * 1.000000), clamp(b * 0.940000))


def t_cool(r, g, b):
    return (clamp(r * 0.940000), clamp(g * 1.000000), clamp(b * 1.060000))


def t_sepia(r, g, b):
    return (clamp((0.393000 * r) + (0.769000 * g) + (0.189000 * b)),
            clamp((0.349000 * r) + (0.686000 * g) + (0.168000 * b)),
            clamp((0.272000 * r) + (0.534000 * g) + (0.131000 * b)))


def _smoothstep(x):
    return x * x * (3.0 - (2.0 * x))


def t_contrast_s_curve(r, g, b):
    return (clamp(_smoothstep(r)), clamp(_smoothstep(g)), clamp(_smoothstep(b)))


def t_teal_orange_strong(r, g, b):
    luma = (0.212600 * r) + (0.715200 * g) + (0.072200 * b)
    shift = (luma - 0.500000) * 2.000000
    return (clamp(r + (0.250000 * shift)),
            clamp(g + (0.050000 * shift)),
            clamp(b - (0.250000 * shift)))


def t_invert(r, g, b):
    return (1.000000 - r, 1.000000 - g, 1.000000 - b)


# ----------------------------------------------------------------------------------------------
# Writers.
# ----------------------------------------------------------------------------------------------

def write_3d(path, size, transform, title, definition, extra_header=None, crlf=False,
             extra_comments=None):
    """Writes one 3D table. Red changes fastest, as the .cube format requires."""
    newline = "\r\n" if crlf else "\n"
    lines = []
    lines.append("# " + os.path.basename(path))
    lines.append("# Generated by generate-luts.py for CodeBrix.VideoPlayback.")
    lines.append("# PUBLIC DOMAIN (CC0 1.0 Universal). No rights reserved.")
    lines.append("# Definition: " + definition)
    for comment in (extra_comments or []):
        lines.append("# " + comment)
    if title is not None:
        lines.append('TITLE "' + title + '"')
    lines.append("LUT_3D_SIZE " + str(size))
    for header_line in (extra_header or []):
        lines.append(header_line)
    lines.append("")

    last = size - 1
    for blue_index in range(size):
        blue = blue_index / last
        for green_index in range(size):
            green = green_index / last
            for red_index in range(size):
                red = red_index / last
                lines.append(row(*transform(red, green, blue)))

    with open(path, "wb") as handle:
        handle.write((newline.join(lines) + newline).encode("ascii"))
    return len(lines)


def write_1d(path, size, curve, title, definition):
    """Writes one 1D table: one row per point, the same curve on all three channels."""
    lines = []
    lines.append("# " + os.path.basename(path))
    lines.append("# Generated by generate-luts.py for CodeBrix.VideoPlayback.")
    lines.append("# PUBLIC DOMAIN (CC0 1.0 Universal). No rights reserved.")
    lines.append("# Definition: " + definition)
    if title is not None:
        lines.append('TITLE "' + title + '"')
    lines.append("LUT_1D_SIZE " + str(size))
    lines.append("")

    last = size - 1
    for index in range(size):
        value = clamp(curve(index / last))
        lines.append(row(value, value, value))

    with open(path, "wb") as handle:
        handle.write(("\n".join(lines) + "\n").encode("ascii"))
    return len(lines)


# ----------------------------------------------------------------------------------------------
# The corpus. The definition strings are the contract the tests may assert against.
# ----------------------------------------------------------------------------------------------

DEFINITIONS = {
    "identity_33.cube":
        "out = in. Row i of each axis holds i/32. States the default domain explicitly.",
    "identity_17.cube":
        "out = in. Row i of each axis holds i/16. Minimal header: no TITLE, no DOMAIN lines.",
    "identity_65.cube":
        "out = in. Row i of each axis holds i/64.",
    "warm_33.cube":
        "out = clamp(in * (1.06, 1.00, 0.94)) per channel.",
    "cool_33.cube":
        "out = clamp(in * (0.94, 1.00, 1.06)) per channel.",
    "sepia_33.cube":
        "out = clamp(M * in), M = [[0.393,0.769,0.189],[0.349,0.686,0.168],"
        "[0.272,0.534,0.131]].",
    "contrast_s_curve_33.cube":
        "out = smoothstep(in) per channel, smoothstep(x) = x*x*(3 - 2*x).",
    "teal_orange_strong_33.cube":
        "luma = 0.2126*r + 0.7152*g + 0.0722*b (Rec.709); shift = (luma - 0.5) * 2; "
        "out = clamp(r + 0.25*shift, g + 0.05*shift, b - 0.25*shift).",
    "invert_33.cube":
        "out = 1 - in per channel, exactly. No clamping is needed and none is applied.",
    "gamma_2_2_1d_1024.cube":
        "1D table, 1024 points. Point i holds x^(1/2.2) on all three channels, x = i/1023.",
    "domain_test_33.cube":
        "DOMAIN_MIN -0.5, DOMAIN_MAX 1.5. The table clamps that declared domain into 0..1: "
        "row i of each axis holds clamp(-0.5 + 2.0*i/32, 0, 1).",
    "crlf_variant_33.cube":
        "out = in, numerically identical to identity_33.cube. Differs only in its bytes: CRLF "
        "line endings, extra comment lines and a TITLE.",
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "generated")
    if not os.path.isdir(out):
        os.makedirs(out)

    d = DEFINITIONS
    written = []

    def note(name, rows):
        written.append((name, rows, os.path.getsize(os.path.join(out, name))))

    name = "identity_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_identity, "Identity 33", d[name],
                        extra_header=["DOMAIN_MIN 0.000000 0.000000 0.000000",
                                      "DOMAIN_MAX 1.000000 1.000000 1.000000"]))

    name = "identity_17.cube"
    note(name, write_3d(os.path.join(out, name), 17, t_identity, None, d[name]))

    name = "identity_65.cube"
    note(name, write_3d(os.path.join(out, name), 65, t_identity, "Identity 65", d[name]))

    name = "warm_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_warm, "Warm 33", d[name]))

    name = "cool_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_cool, "Cool 33", d[name]))

    name = "sepia_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_sepia, "Sepia 33", d[name]))

    name = "contrast_s_curve_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_contrast_s_curve, "Contrast S Curve 33",
                        d[name]))

    name = "teal_orange_strong_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_teal_orange_strong,
                        "Teal and Orange Strong 33", d[name]))

    name = "invert_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_invert, "Invert 33", d[name]))

    name = "gamma_2_2_1d_1024.cube"
    note(name, write_1d(os.path.join(out, name), 1024, lambda x: x ** (1.0 / 2.2),
                        "Gamma 2.2 Encode 1D", d[name]))

    name = "domain_test_33.cube"

    def t_domain(r, g, b):
        # r, g, b arrive as i/32; the declared domain is -0.5..1.5, so the input this row
        # stands for is -0.5 + 2.0 * (i/32), and the table clamps it into 0..1.
        return (clamp(-0.5 + (2.0 * r)), clamp(-0.5 + (2.0 * g)), clamp(-0.5 + (2.0 * b)))

    note(name, write_3d(os.path.join(out, name), 33, t_domain, "Domain Test 33", d[name],
                        extra_header=["DOMAIN_MIN -0.500000 -0.500000 -0.500000",
                                      "DOMAIN_MAX 1.500000 1.500000 1.500000"]))

    name = "crlf_variant_33.cube"
    note(name, write_3d(os.path.join(out, name), 33, t_identity, "CRLF Variant Identity 33",
                        d[name], crlf=True,
                        extra_comments=["This file uses CRLF line endings throughout.",
                                        "It exists so the reader is proved against files exported",
                                        "on Windows, which is most of them.",
                                        ""]))

    total = 0
    for name, rows, size in written:
        total += size
        print("%-30s %8d lines %10d bytes" % (name, rows, size))
    print("%-30s %8s       %10d bytes" % ("TOTAL", len(written), total))


if __name__ == "__main__":
    main()
